### ISSUE TITLE
BUG: redirect_uri - invalid value

### ISSUE THREAD

**Issue by friendlyantz** [failure-driven/square-snippet-demo#1]
https://stg-swif.herokuapp.com/users/sign_in
Heroku Error: loging redirect_uri when trying to login 
<img width="771" alt="image" src="https://user-images.githubusercontent.com/70934030/120925058-0dd3e600-c71a-11eb-9a66-9ab1ef479302.png">

![image](https://user-images.githubusercontent.com/70934030/120992928-695bad80-c7c6-11eb-88ba-921fd8cf5243.png)

tried on firefox and Chrome(both signed in, and new sign in)

**Comment by saramic** [comment]
stg-swif was using the same return credentials (https://swif.club) as production so have removed it for the time being to reduce confusion with https://github.com/failure-driven/square-snippet-demo/commit/83e52fb1fd64058493acabe0b10d7ce0e824a453

feel free to run in development mode and in production on (https://swif.club)
